version: "3.7"
services:

  db:
    container_name: db
    image: postgres:11.4
    hostname: db
    command: postgres -c 'max_connections=150'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  betting-project:
    image: vstamos.private:30225/betting-project
    container_name: betting-project
    ports:
      - 4000:4000